window.mockDatabase = {
  "特效": [
    {
      "id": 1,
      "title": "摄像机运镜技巧：伏羲驯六畜",
      "category": "effects",
      "categoryName": "AE特效",
      "date": "2025-07-08",
      "description": "展示如何通过AE摄像机以及相关技巧制作丝滑流畅的运镜效果...",
      "content": "",
      "url": "./content/ae-effects/eff_detail_001.html"
    }
  ],
  "表达": [
    {
      "id": 1,
      "title": "表达式保姆级教程零基础15模块实战",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2025-08-04",
      "description": "全网最系统的表达式入门指南！小白也能三天上手自动化动画！",
      "content": "",
      "url": "./content/ae-expressions/exp_basic_001.html"
    },
    {
      "id": 2,
      "title": "表达式保姆级教程之导言",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2025-08-07",
      "description": "学习如何使用表达式创建复杂的动态动画效果，提升项目水平...",
      "content": "",
      "url": "./content/ae-expressions/exp_basic_002.html"
    },
    {
      "id": 3,
      "title": "表达式制作丝滑的倒计时效果",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2025-01-12",
      "description": "使用简单的表达式制作数字倒计时...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_001.html"
    },
    {
      "id": 4,
      "title": "正余弦三角形绕圆周路径运动",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2025-01-21",
      "description": "使用表达式正余弦函数及路径创建函数制作三角形绕圆周运动...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_002.html"
    },
    {
      "id": 5,
      "title": "表达式三维物体圆周运动",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2025-01-27",
      "description": "使用表达式正余弦函数及路径创建函数制作三角形绕圆周运动...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_003.html"
    },
    {
      "id": 6,
      "title": "表达式歌词逐字变色效果",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-06-01",
      "description": "使用表达式制作歌词逐字变色卡拉OK效果...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_004.html"
    },
    {
      "id": 7,
      "title": "旋转木马立体三维空间旋转",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-06-15",
      "description": "使用表达式制作图片等始终朝向目标三维旋转...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_005.html"
    },
    {
      "id": 8,
      "title": "法线感知双面显隐控制朝向透明度",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-06-22",
      "description": "使用表达式制作物品双面显隐...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_006.html"
    },
    {
      "id": 9,
      "title": "活体遮罩焊死旋转边界",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-06-29",
      "description": "使用表达式制作焊死图片边界的遮罩...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_007.html"
    },
    {
      "id": 10,
      "title": "顶点感知拓扑法则连线",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-06",
      "description": "使用表达式制作顶点感知自动生成拓扑连线...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_008.html"
    },
    {
      "id": 11,
      "title": "字符流光标脉冲打字机效果",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-13",
      "description": "使用表达式制作带有光标脉冲的打字机效果...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_009.html"
    },
    {
      "id": 12,
      "title": "标记点时间差驱动歌词变色",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-16",
      "description": "使用表达式标记点时间差驱动歌词逐个变色效果...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_010.html"
    },
    {
      "id": 13,
      "title": "表达式曲线绘制浪漫爱心",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-20",
      "description": "根据参数方程使用表达式绘制浪漫爱心形状...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_011.html"
    },
    {
      "id": 14,
      "title": "表达式条件判断逗号的迷惑行为",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-23",
      "description": "解释表达式条件判断里逗号的迷惑行为...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_012.html"
    },
    {
      "id": 15,
      "title": "表达式梯度递进韵律文字",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-07-27",
      "description": "表达式文字逐个变大，自己长出节奏感...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_013.html"
    },
    {
      "id": 16,
      "title": "表达式制作文本快切",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-08-02",
      "description": "无需K帧，表达式轻松制作文本快切...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_014.html"
    },
    {
      "id": 17,
      "title": "循环动画停止再循环",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-08-04",
      "description": "如何让循环动画停止两秒再循环...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_015.html"
    },
    {
      "id": 18,
      "title": "五彩斑澜文字制作",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-08-10",
      "description": "表达式制作五彩斑澜的文字...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_016.html"
    },
    {
      "id": 19,
      "title": "视频循环三种方法",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-08-17",
      "description": "三种方法制作视频循环...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_017.html"
    },
    {
      "id": 20,
      "title": "表达式图片快闪",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-08-31",
      "description": "表达式制作图片快闪轮播...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_018.html"
    },
    {
      "id": 21,
      "title": "表达式控制循环停止时间和次数",
      "category": "expressions",
      "categoryName": "AE表达式",
      "date": "2026-09-06",
      "description": "表达式控制循环停止时间和次数...",
      "content": "",
      "url": "./content/ae-expressions/exp_detail_019.html"
    }
  ],
  "脚本": [
    {
      "id": 1,
      "title": "AE脚本开发零基础入门教程之片头介绍",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-02-03",
      "description": "学习如何编写AE脚本，自动化重复任务并提高工作效率...",
      "content": "",
      "url": "./content/ae-scripting/src_basic_001.html"
    },
    {
      "id": 2,
      "title": "AE脚本开发教程之第一章第一节",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-02-06",
      "description": "学习AE脚本基础知识，了解什么是AE脚本...",
      "content": "",
      "url": "./content/ae-scripting/src_basic_002.html"
    },
    {
      "id": 3,
      "title": "AE脚本开发教程之第一章第二节",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-02-10",
      "description": "学习AE脚本基础知识，了解脚本、表达式和插件的区别...",
      "content": "",
      "url": "./content/ae-scripting/src_basic_003.html"
    },
    {
      "id": 4,
      "title": "AE脚本开发教程之第一章第三节",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-02-17",
      "description": "学习AE脚本基础知识，配置AE脚本的开发环境",
      "content": "",
      "url": "./content/ae-scripting/src_basic_004.html"
    },
    {
      "id": 5,
      "title": "AE脚本开发教程之第一章第四节",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-02-24",
      "description": "学习AE脚本基础知识，输出第一个hello world脚本",
      "content": "",
      "url": "./content/ae-scripting/src_basic_005.html"
    },
    {
      "id": 6,
      "title": "AE表达式自学神器",
      "category": "scripting",
      "categoryName": "AE脚本",
      "date": "2025-08-24",
      "description": "一款AE脚本，能让你轻松学习表达式",
      "content": "",
      "url": "./content/ae-scripting/src_detail_001.html"
    }
  ],
  "插件": [
    {
      "id": 1,
      "title": "Premiere Pro UXP插件开发入门",
      "category": "plugins",
      "categoryName": "AE插件",
      "date": "2026-02-01",
      "description": "探索Adobe新一代UXP平台，学习现代化AE插件开发技术...",
      "content": "",
      "url": "./content/ae-plugins/plg_basic_001.html"
    }
  ],
  "软件": [
    {
      "id": 1,
      "title": "AE脚本UI设计器安装激活向导",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2025-10-29",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_001.html"
    },
    {
      "id": 2,
      "title": "AE脚本UI设计器使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2025-10-29",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_002.html"
    },
    {
      "id": 3,
      "title": "MarkdownToHtml转换器使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2025-11-11",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_003.html"
    },
    {
      "id": 4,
      "title": "PDF水印添加工具使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2025-11-24",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_004.html"
    },
    {
      "id": 5,
      "title": "AE英文界面学习助手v1.0.0使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2025-12-08",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_005.html"
    },
    {
      "id": 6,
      "title": "AE英文界面学习助手v2.0.0更新指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2026-01-14",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_006.html"
    },
    {
      "id": 7,
      "title": "文本转语音工具TTS v1.0.0使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2026-01-19",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_007.html"
    },
    {
      "id": 8,
      "title": "音梳 Audio Comber v1.0.0使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2026-01-26",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_008.html"
    },
    {
      "id": 9,
      "title": "音梳 Audio Comber v2.0.0使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2026-02-12",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_009.html"
    },
    {
      "id": 10,
      "title": "AE表达式防瞟窃神器 v2.0.0使用指南",
      "category": "software",
      "categoryName": "软件指南",
      "date": "2026-04-08",
      "description": "",
      "content": "",
      "url": "./content/software/sof_detail_010.html"
    }
  ],
  "下载": [
    {
      "id": 1,
      "title": "Adobe After Effects 脚本开发指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "AE脚本开发核心手册，系统讲解ExtendScript语法与AE对象模型，涵盖自动化流程及API调用，是定制化工作流的技术基石。",
      "size": "4.1 MB",
      "downloads": 2450,
      "type": "script",
      "url": "https://pan.baidu.com/s/1Wth1W9abKGBeW_yob-cypQ?pwd=4ugp",
      "date": "2024-10-15"
    },
    {
      "id": 2,
      "title": "ExtendScript ScriptUI 开发指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "专注ScriptUI界面设计，提供控件创建、布局优化及事件处理方案，助力开发者构建直观的AE脚本交互界面，提升用户体验。",
      "size": "2.2 MB",
      "downloads": 11098,
      "type": "script",
      "url": "https://pan.baidu.com/s/1wUfBYdi2kQu0JVGUY_-GoA?pwd=6pd7",
      "date": "2024-10-10"
    },
    {
      "id": 3,
      "title": "AE表达式自学神器AE_Expr_Tool v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "原创AE脚本，一键查询内置表达式功能说明并配备用法示例，支持快速为选中图层属性添加自定义表达式，提升表达式编辑效率，适合动画师与特效师使用。",
      "size": "732 KB",
      "downloads": 1026,
      "type": "script",
      "url": "../../assets/downloads/scripts/layer-manager.zip",
      "date": "2024-10-05"
    },
    {
      "id": 4,
      "title": "AE脚本开发全套视频教程及配套文档",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "原创After Effects ExtendScript 脚本开发视频教程，包含脚本开发及scriptUI设计教程，并配有章节文档，提高用户脚本开发能力。",
      "size": "5.35 GB",
      "downloads": 329,
      "type": "script",
      "url": "../../assets/downloads/scripts/layer-manager.zip",
      "date": "2025-02-08"
    },
    {
      "id": 5,
      "title": "AE效果属性匹配名称查询工具",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "一款通过输入AE本地化名称可以查询到相应的匹配名称工具，配有使用文档，提高用户脚本开发效率。",
      "size": "733 KB",
      "downloads": 2646,
      "type": "script",
      "url": "https://pan.baidu.com/s/1P_qHeSXHht3lJyDevSZJjg?pwd=6yif",
      "date": "2018-08-01"
    },
    {
      "id": 6,
      "title": "图片转码脚本Base64Imager v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "Base64Imager v1.0 是一款能够将图片文件转换成Base64编码格式脚本，适合网页动画制作、UI设计和需要内嵌图片资源的项目",
      "size": "682 KB",
      "downloads": 1957,
      "type": "script",
      "url": "https://pan.baidu.com/s/1vDiSgpvgxEaNeQHojMxW5w?pwd=p8pf",
      "date": "2018-08-08"
    },
    {
      "id": 7,
      "title": "素材搜索器MaterialSearch v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "素材搜索器是一款专为Adobe After Effects设计的效率工具，支持模糊搜索项目面板中的素材，并通过直观的界面快速定位目标素材，大幅提升工作流程效率。",
      "size": "726 KB",
      "downloads": 1153,
      "type": "script",
      "url": "https://pan.baidu.com/s/14rHo6-Yrur059jOido6xJw?pwd=u5xh",
      "date": "2025-10-10"
    },
    {
      "id": 8,
      "title": "素材搜索器MaterialSearch v2.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "素材搜索器 v2.0在v1.0搜索功能基础上新增了素材导入和替换功能。支持模糊搜索项目面板中的素材，快速定位目标素材，并能够安全地导入和替换素材。",
      "size": "782 KB",
      "downloads": 1641,
      "type": "script",
      "url": "https://pan.baidu.com/s/1Urg9_sVvMeVTXwK4Gh-lCQ?pwd=c4u6",
      "date": "2025-10-13"
    },
    {
      "id": 9,
      "title": "图层离散器Layer Disperser v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "图层离散器是一款专业图层离散化脚本。它通过先进的离散算法，将单一图层智能拆解为具有空间分布的多元素组合，广泛应用于动态图形设计、视觉特效制作、片头包装等领域.",
      "size": "823 KB",
      "downloads": 3521,
      "type": "script",
      "url": "https://pan.baidu.com/s/1Rq_s8uSqjP_GFZkegl7TQw?pwd=e7i9",
      "date": "2025-10-15"
    },
    {
      "id": 10,
      "title": "字符串转Unicode v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "一款专为AE脚本开发者设计的专业安全工具。通过将明文字符串转换为Unicode转义序列，保护脚本中的敏感信息，如注册密钥、授权码等，防止普通用户直接查看源代码中的关键数据。",
      "size": "765 KB",
      "downloads": 1052,
      "type": "script",
      "url": "https://pan.baidu.com/s/1byMUc6T5GvlfbN8-cwNtkg?pwd=a673",
      "date": "2025-10-16"
    },
    {
      "id": 11,
      "title": "Unicode转义序列转字符串 v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "Unicode转义序列转字符串工具是一款专为After Effects脚本开发者设计的专业安全工具。本产品通过将Unicode转义序列转换为明文字符串。",
      "size": "713 KB",
      "downloads": 1627,
      "type": "script",
      "url": "https://pan.baidu.com/s/1vPcRUo_RXBh6Rkh_Ucxq3g?pwd=s5yh",
      "date": "2025-10-16"
    },
    {
      "id": 12,
      "title": "属性路径获取工具 v1.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "Property Path Generator 是一款专业的 After Effects 脚本工具，专门为 AE 脚本开发者设计。它可以自动生成精确的属性引用路径代码，极大提高开发效率。",
      "size": "773 KB",
      "downloads": 2162,
      "type": "script",
      "url": "https://pan.baidu.com/s/1JbbKiBCtIvFbTfFMfQPlig?pwd=jy7d",
      "date": "2025-10-24"
    },
    {
      "id": 13,
      "title": "预合成助手 PreComp Assistant v2.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "预合成助手是一款专业的After Effects脚本工具，用于简化预合成和解预合成操作。通过智能的时间保持和图层顺序管理，让您的合成工作流程更加高效顺畅。",
      "size": "763 KB",
      "downloads": 3018,
      "type": "script",
      "url": "https://pan.baidu.com/s/1Zy1U_dvVeT7FbF1qTpf6rw?pwd=ixf3",
      "date": "2025-10-27"
    },
    {
      "id": 14,
      "title": "批量表达式助手 BatchExpr v2.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "批量表达式助手 (BatchExpr) After Effects 脚本工具。可以批量给图层属性添加表达式，并能够删除属性上已经存在的表达式。",
      "size": "522 KB",
      "downloads": 156,
      "type": "script",
      "url": "https://pan.baidu.com/s/1I3vrwMKuO5SGcrefLEhEmw?pwd=bgce",
      "date": "2026-08-24"
    },
    {
      "id": 101,
      "title": "Adobe After Effects表达式官方文档",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "AE表达式官方文档详细解析了JS语法在动画控制中的核心应用，涵盖基础运算符、时间轴控制、对象属性绑定等关键功能，是动态图形设计的权威技术指南。",
      "size": "694 KB",
      "downloads": 1765,
      "type": "expression",
      "url": "https://pan.baidu.com/s/1aqIphvWt9ETwWQovlh_Sqg?pwd=uxx8",
      "date": "2024-09-28"
    },
    {
      "id": 102,
      "title": "AE表达式视频教程",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "零基础入门到精通，表达式视频教程。包含15个章节。配有相应的表达式工程文件及解说文档",
      "size": "7.8 GB",
      "downloads": 552,
      "type": "expression",
      "url": "../../assets/downloads/expressions/expression-presets.zip",
      "date": "2024-09-15"
    },
    {
      "id": 201,
      "title": "Premiere Pro UXP 插件开发系统教程",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "让Premiere听懂你的指令。通过UXP开发增效面板，把复杂流程一键封装，从剪辑师进阶为工具创造者。",
      "size": "6.15 GB",
      "downloads": 1039,
      "type": "plugin",
      "url": "../../assets/downloads/templates/text-animations.zip",
      "date": "2026-05-20"
    },
    {
      "id": 202,
      "title": "Adobe After Effects UXP 插件开发入门指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "为AE注入灵魂！告别重复操作，开启UXP插件开发之旅，从使用者变身创造者，打造专属神器",
      "size": "6.9 GB",
      "downloads": 678,
      "type": "plugin",
      "url": "../../assets/downloads/templates/text-animations.zip",
      "date": "2024-08-20"
    },
    {
      "id": 203,
      "title": "UXP JavaScript API 与开发指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "这份文档详细介绍了 UXP 插件的核心 JavaScript API 及基本开发流程与方法。",
      "size": "4.8 MB",
      "downloads": 1324,
      "type": "plugin",
      "url": "https://pan.baidu.com/s/19acCU_yFJFCjq1FnnMsG_A?pwd=de6k",
      "date": "2024-09-10"
    },
    {
      "id": 204,
      "title": "UXP 样式与 CSS 指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "该指南说明了如何使用 CSS 来定义和美化 UXP 插件用户界面的外观与样式。",
      "size": "723 KB",
      "downloads": 1543,
      "type": "plugin",
      "url": "https://pan.baidu.com/s/1Qw0P-5OlR7Sb4PiSh_vfow?pwd=eedr",
      "date": "2024-09-05"
    },
    {
      "id": 205,
      "title": "UXP 界面结构与 HTML 指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "本指南阐述了如何使用 HTML 来构建和定义 UXP 插件的用户界面基础结构。",
      "size": "466 KB",
      "downloads": 1876,
      "type": "plugin",
      "url": "https://pan.baidu.com/s/1D6NTBRHGYoxu_xPmqlGFDg?pwd=irpm",
      "date": "2024-08-28"
    },
    {
      "id": 206,
      "title": "Adobe Spectrum组件库指南",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "此指南介绍了如何调用官方的 Spectrum UI 组件库，以确保插件界面与 Adobe 家族风格一致。",
      "size": "7.9 MB",
      "downloads": 1876,
      "type": "plugin",
      "url": "https://pan.baidu.com/s/1uzIDb3uwxQJqOl-xj07tZg?pwd=uruc",
      "date": "2024-08-25"
    },
    {
      "id": 301,
      "title": "AE表达式-条件逻辑(If语句)工程文件",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "该AE工程文件通过具体示例，演示了if条件语句在After Effects表达式中的编写语法与应用方法。",
      "size": "249 KB",
      "downloads": 2210,
      "type": "template",
      "url": "https://pan.baidu.com/s/1zoQ2vuOm51nXhjAbrCK9LA?pwd=h3de",
      "date": "2024-08-15"
    },
    {
      "id": 401,
      "title": "AE脚本界面设计器ScriptUI Designer v1.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "AE脚本UI设计器是一款专业的AE脚本用户界面设计工具，帮助用户快速设计和生成AE脚本的UI界面。请在【软件指南】栏目查看相关下载以及购买使用视频",
      "size": "92 MB",
      "downloads": 276,
      "type": "software",
      "url": "https://pan.baidu.com/s/16jn8BpSuvXqceltcQjLdBw?pwd=b26n",
      "date": "2025-10-29"
    },
    {
      "id": 402,
      "title": "MarkdownToHtml转换器Markdown Wizard v1.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "一款轻量级桌面应用，集编辑、转换、预览于一体，让你的写作与发布流程无缝衔接。请在【软件指南】栏目查看相关使用视频",
      "size": "73.5 MB",
      "downloads": 953,
      "type": "software",
      "url": "https://pan.baidu.com/s/1D3d7UhWkZ27FFjYii_It-A?pwd=k8xd",
      "date": "2025-11-11"
    },
    {
      "id": 403,
      "title": "PDF水印添加工具PDF Watermark Tool v1.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "PDF Watermark Tool 是一款专业的PDF水印添加工具，支持快速为PDF文档添加自定义水印。请在【软件指南】栏目查看相关使用视频",
      "size": "66.8 MB",
      "downloads": 325,
      "type": "software",
      "url": "https://pan.baidu.com/s/1J0iPlm5XHUvQ9OJ1qG34Cw?pwd=bq5a",
      "date": "2025-11-24"
    },
    {
      "id": 404,
      "title": "AE英文学习助手AE Terminology learning v1.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "AE英文界面学习助手是一款帮助英文基础薄弱的用户快速熟悉和掌握AE英文版界面中的专业术语。请在【软件指南】栏目查看相关使用视频",
      "size": "68.6 MB",
      "downloads": 975,
      "type": "software",
      "url": "https://pan.baidu.com/s/1Goj5vNN6i4hU1UBJZ0jTng?pwd=ni5p",
      "date": "2025-12-08"
    },
    {
      "id": 405,
      "title": "AE英文学习助手AE Word Master v2.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "AE英文界面学习助手是一款帮助英文基础薄弱的用户快速熟悉和掌握AE英文版界面中的专业术语。请在【软件指南】栏目查看相关使用视频",
      "size": "75 MB",
      "downloads": 1026,
      "type": "software",
      "url": "https://pan.baidu.com/s/1muKzxJsYuPNQUhpX-FG2ng?pwd=2vgv",
      "date": "2026-01-14"
    },
    {
      "id": 406,
      "title": "文本转语音合成工具TTS",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "文本转语音合成工具TTS是一款能够将文本转成语音的工具。请在【软件指南】栏目查看相关使用视频",
      "size": "73 MB",
      "downloads": 568,
      "type": "software",
      "url": "#",
      "date": "2026-01-26"
    },
    {
      "id": 407,
      "title": "音梳 v1.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "音梳(Audio Comber)是一款专业音效管理工具。它能够帮助您高效地管理、预览、处理和导出音频素材。请在【软件指南】栏目查看相关使用视频",
      "size": "98.6 MB",
      "downloads": 1236,
      "type": "software",
      "url": "https://pan.baidu.com/s/1ESdpjIE62YJJZPhRpmVVfA?pwd=2g7b",
      "date": "2026-01-26"
    },
    {
      "id": 408,
      "title": "音梳 v2.0.0",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "音梳(Audio Comber)是一款专业音效管理工具。它能够帮助您高效地管理、预览、处理和导出音频素材。请在【软件指南】栏目查看相关使用视频",
      "size": "175 MB",
      "downloads": 669,
      "type": "software",
      "url": "#",
      "date": "2026-02-12"
    },
    {
      "id": 501,
      "title": "Adobe UXP Developer Tools",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "Adobe官方提供的插件开发工具集，专门用于在现代 UXP 平台上为 Creative Cloud 应用程序（如 PS、PR、AE）开发插件。",
      "size": "3.1 MB",
      "downloads": 2987,
      "type": "toolkit",
      "url": "https://creativecloud.adobe.com/apps/download/uxp-developer-tools",
      "date": "2025-02-10"
    },
    {
      "id": 502,
      "title": "RGB颜色对照表",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "该文档汇编了各种颜色的英文名称、RGB数值、实色效果块及其对应的16进制颜色代码。",
      "size": "353 KB",
      "downloads": 1987,
      "type": "toolkit",
      "url": "https://pan.baidu.com/s/1khTvZ4gvobQBJqfJYoJfTg?pwd=fmmd",
      "date": "2024-08-05"
    },
    {
      "id": 503,
      "title": "Adobe ExtendScript Toolkit CC",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "ESTK是Adobe系列软件的专用脚本编辑器，用于编写和调试ExtendScript脚本，以自动化执行Photoshop、AE等软件任务。",
      "size": "93.8 MB",
      "downloads": 416,
      "type": "toolkit",
      "url": "https://pan.baidu.com/s/1Zf2bDv2EWqF16Kkmj-Km4Q?pwd=pgwc",
      "date": "2010-08-06"
    },
    {
      "id": 504,
      "title": "Visual Studio Code",
      "category": "downloads",
      "categoryName": "资源下载",
      "description": "VS Code是一款轻量级代码编辑器，支持多种编程语言，具备强大的扩展功能，帮助开发者高效编写、调试和管理项目。",
      "size": "98.6 MB",
      "downloads": 3432,
      "type": "toolkit",
      "url": "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user",
      "date": "2025-08-06"
    }
  ]
};