# 站点设置
title: 我的博客
email: hlm_0904@163.com
description: >- 
  记录AE脚本插件开发经验
baseurl: "" 
url: "https://szsoar.github.io"
github_username:  szsoar

# 新增的显示文本配置
display_settings:
  browser_title: "欢迎来到我的博客"
  navbar_title: "szsoar"
  header_title: "老胡的技术博客"
  header_subtitle: "专注After Effects脚本插件开发 | 分享AE扩展开发经验"
  footer_name: "szsoar"

# 社交媒体链接
social_links:
  - platform: email
    user_url: "mailto:{{ site.email }}"
  - platform: github
    user_url: "https://github.com/szsoar"
  - platform: bilibili
    user_url: "https://space.bilibili.com/3546734150028132"
  - platform: douyin
    user_url: "https://v.douyin.com/Y6r0eNKeK10"

# 构建设置
theme: minima
plugins:
  - jekyll-feed

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
