plugins:
  - jekyll-paginate

timezone: Asia/Shanghai  # 指定为北京时间（UTC+8）
future: false            # 明确禁止未来文章（默认值，但建议显式声明）

title: 我的博客
description: 记录AE脚本插件开发经验
baseurl: "" 
url: "https://szsoar.github.io"

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 作者信息
author:
  name: szsoar
  email: hlm_0904@163.com
  github: szsoar
  twitter: szsoar
  linkedin: szsoar

# 社交媒体
github_username: szsoar
twitter_username: szsoar
linkedin_username: szsoar
email: hlm_0904@163.com

# 主题设置
theme: jekyll-theme-minimal

# 排除无关目录（避免符号链接错误）
exclude:
  - vendor/
  - Gemfile.lock


