// 下载资源数据
const downloadsData = [
  // ==================== 脚本分类 ====================
  {
    id: 1,
    title: "Adobe After Effects 脚本开发指南",
    category: "script",
    description: "AE脚本开发核心手册，系统讲解ExtendScript语法与AE对象模型，涵盖自动化流程及API调用，是定制化工作流的技术基石。",
    icon: "📑",
    fileSize: "4.1 MB",
    version: "文档",
    downloadCount: 2450,
    url: "https://pan.baidu.com/s/1Wth1W9abKGBeW_yob-cypQ?pwd=4ugp",
    date: "2024-10-15",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 2,
    title: "ExtendScript ScriptUI 开发指南",
    category: "script",
    description: "专注ScriptUI界面设计，提供控件创建、布局优化及事件处理方案，助力开发者构建直观的AE脚本交互界面，提升用户体验。",
    icon: "📄",
    fileSize: "2.2 MB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1wUfBYdi2kQu0JVGUY_-GoA?pwd=6pd7",
    date: "2024-10-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 3,
    title: "AE表达式自学神器AE_Expr_Tool v1.0",
    category: "script",
    description: "原创AE脚本，一键查询内置表达式功能说明并配备用法示例，支持快速为选中图层属性添加自定义表达式，提升表达式编辑效率，适合动画师与特效师使用。",
    icon: "⚙️",
    fileSize: "732 KB",
    version: "原创脚本",
    downloadCount: 618,
    url: "../../assets/downloads/scripts/layer-manager.zip",
    date: "2024-10-05",
    priceType: "收费",
    price: "¥35.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 4,
    title: "AE脚本开发全套视频教程及配套文档",
    category: "script",
    description: "原创After Effects ExtendScript 脚本开发视频教程，包含脚本开发及scriptUI设计教程，并配有章节文档，提高用户脚本开发能力。",
    icon: "🎬",
    fileSize: "9.40 GB",
    version: "视频教程文档",
    downloadCount: 38,
    url: "../../assets/downloads/scripts/layer-manager.zip",
    date: "2025-02-08",
    priceType: "收费",
    price: "¥298.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 5,
    title: "AE效果属性匹配名称查询工具",
    category: "script",
    description: "一款通过输入AE本地化名称可以查询到相应的匹配名称工具，配有使用文档，提高用户脚本开发效率。",
    icon: "⚙️",
    fileSize: "733 KB",
    version: "原创脚本",
    downloadCount: 2646,
    url: "https://pan.baidu.com/s/1P_qHeSXHht3lJyDevSZJjg?pwd=6yif",
    date: "2018-08-01",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 6,
    title: "图片转码脚本Base64Imager v1.0",
    category: "script",
    description: "Base64Imager v1.0 是一款能够将图片文件转换成Base64编码格式脚本，适合网页动画制作、UI设计和需要内嵌图片资源的项目",
    icon: "⚙️",
    fileSize: "682 KB",
    version: "原创脚本",
    downloadCount: 1957,
    url: "https://pan.baidu.com/s/1vDiSgpvgxEaNeQHojMxW5w?pwd=p8pf",
    date: "2018-08-08",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 7,
    title: "素材搜索器MaterialSearch v1.0",
    category: "script",
    description: "素材搜索器是一款专为Adobe After Effects设计的效率工具，支持模糊搜索项目面板中的素材，并通过直观的界面快速定位目标素材，大幅提升工作流程效率。",
    icon: "⚙️",
    fileSize: "726 KB",
    version: "原创脚本",
    downloadCount: 1153,
    url: "https://pan.baidu.com/s/14rHo6-Yrur059jOido6xJw?pwd=u5xh",
    date: "2025-10-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 8,
    title: "素材搜索器MaterialSearch v2.0",
    category: "script",
    description: "素材搜索器 v2.0在v1.0搜索功能基础上新增了素材导入和替换功能。支持模糊搜索项目面板中的素材，快速定位目标素材，并能够安全地导入和替换素材。",
    icon: "⚙️",
    fileSize: "782 KB",
    version: "原创脚本",
    downloadCount: 1641,
    url: "https://pan.baidu.com/s/1Urg9_sVvMeVTXwK4Gh-lCQ?pwd=c4u6",
    date: "2025-10-13",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },

  // ==================== 表达式分类  ====================
  {
    id: 101,
    title: "Adobe After Effects表达式官方文档",
    category: "expression",
    description: "AE表达式官方文档详细解析了JS语法在动画控制中的核心应用，涵盖基础运算符、时间轴控制、对象属性绑定等关键功能，是动态图形设计的权威技术指南。",
    icon: "📜",
    fileSize: "694 KB",
    version: "文档",
    downloadCount: 1765,
    url: "https://pan.baidu.com/s/1aqIphvWt9ETwWQovlh_Sqg?pwd=uxx8",
    date: "2024-09-28",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 102,
    title: "AE表达式视频教程",
    category: "expression",
    description: "零基础入门到精通，表达式视频教程。包含15个章节。配有相应的表达式工程文件及解说文档",
    icon: "▶️",
    fileSize: "7.8 GB",
    version: "视频教程",
    downloadCount: 87,
    url: "../../assets/downloads/expressions/expression-presets.zip",
    date: "2024-09-15",
    priceType: "收费",
    price: "¥198.00",
    qrCode: "../../assets/images/qq_image.png"
  },

  // ==================== 插件分类  ====================
  {
    id: 201,
    title: "UXP JavaScript API 与开发指南",
    category: "plugin",
    description: "这份文档详细介绍了 UXP 插件的核心 JavaScript API 及基本开发流程与方法。",
    icon: "📋",
    fileSize: "4.8 MB",
    version: "文档",
    downloadCount: 1324,
    url: "https://pan.baidu.com/s/19acCU_yFJFCjq1FnnMsG_A?pwd=de6k",
    date: "2024-09-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 202,
    title: "UXP 样式与 CSS 指南",
    category: "plugin",
    description: "该指南说明了如何使用 CSS 来定义和美化 UXP 插件用户界面的外观与样式。",
    icon: "📚",
    fileSize: "723 KB",
    version: "文档",
    downloadCount: 1543,
    url: "https://pan.baidu.com/s/1Qw0P-5OlR7Sb4PiSh_vfow?pwd=eedr",
    date: "2024-09-05",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 203,
    title: "UXP 界面结构与 HTML 指南",
    category: "plugin",
    description: "本指南阐述了如何使用 HTML 来构建和定义 UXP 插件的用户界面基础结构。",
    icon: "✏️",
    fileSize: "466 KB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1D6NTBRHGYoxu_xPmqlGFDg?pwd=irpm",
    date: "2024-08-28",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 204,
    title: "Adobe Spectrum组件库指南",
    category: "plugin",
    description: "此指南介绍了如何调用官方的 Spectrum UI 组件库，以确保插件界面与 Adobe 家族风格一致。",
    icon: "📝",
    fileSize: "7.9 MB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1uzIDb3uwxQJqOl-xj07tZg?pwd=uruc",
    date: "2024-08-25",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 205,
    title: "Adobe After Effects UXP 插件开发入门指南",
    category: "plugin",
    description: "为AE注入灵魂！告别重复操作，开启UXP插件开发之旅，从使用者变身创造者，打造专属神器",
    icon: "📹",
    fileSize: "8.9 GB",
    version: "视频教程",
    downloadCount: 678,
    url: "../../assets/downloads/templates/text-animations.zip",
    date: "2024-08-20",
    priceType: "收费",
    price: "¥598.00",
    qrCode: "../../assets/images/qq_image.png"
  },

  // ==================== 项目模板分类  ====================

  {
    id: 301,
    title: "AE表达式-条件逻辑(If语句)工程文件",
    category: "template",
    description: "该AE工程文件通过具体示例，演示了if条件语句在After Effects表达式中的编写语法与应用方法。",
    icon: "🔄",
    fileSize: "249 KB",
    version: "工程文件",
    downloadCount: 2210,
    url: "https://pan.baidu.com/s/1zoQ2vuOm51nXhjAbrCK9LA?pwd=h3de",
    date: "2024-08-15",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },

  // ==================== 工具包分类  ====================
  {
    id: 401,
    title: "Adobe UXP Developer Tools",
    category: "toolkit",
    description: "Adobe官方提供的插件开发工具集，专门用于在现代 UXP 平台上为 Creative Cloud 应用程序（如 PS、PR、AE）开发插件。",
    icon: "🔧",
    fileSize: "3.1 MB",
    version: "v2.1",
    downloadCount: 2987,
    url: "https://creativecloud.adobe.com/apps/download/uxp-developer-tools",
    date: "2025-02-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 402,
    title: "RGB颜色对照表",
    category: "toolkit",
    description: "该文档汇编了各种颜色的英文名称、RGB数值、实色效果块及其对应的16进制颜色代码。",
    icon: "🎨",
    fileSize: "353 KB",
    version: "文档",
    downloadCount: 1987,
    url: "https://pan.baidu.com/s/1khTvZ4gvobQBJqfJYoJfTg?pwd=fmmd",
    date: "2024-08-05",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 403,
    title: "Adobe ExtendScript Toolkit CC",
    category: "toolkit",
    description: "ESTK是Adobe系列软件的专用脚本编辑器，用于编写和调试ExtendScript脚本，以自动化执行Photoshop、AE等软件任务。",
    icon: "⌨️",
    fileSize: "93.8 MB",
    version: "v4.0.0.1",
    downloadCount: 416,
    url: "https://pan.baidu.com/s/1Zf2bDv2EWqF16Kkmj-Km4Q?pwd=pgwc",
    date: "2010-08-06",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 404,
    title: "Visual Studio Code",
    category: "toolkit",
    description: "VS Code是一款轻量级代码编辑器，支持多种编程语言，具备强大的扩展功能，帮助开发者高效编写、调试和管理项目。",
    icon: "🔨",
    fileSize: "98.6 MB",
    version: "v1.104.2",
    downloadCount: 3432,
    url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user",
    date: "2025-08-06",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },

];