// 下载资源数据
const downloadsData = [
  // ==================== 脚本分类 ====================
  {
    id: 1,
    title: "Adobe After Effects 脚本开发指南",
    category: "script",
    description: "AE脚本开发核心手册，系统讲解ExtendScript语法与AE对象模型，涵盖自动化流程及API调用，是定制化工作流的技术基石。",
    icon: "📑",
    fileSize: "4.1 MB",
    version: "文档",
    downloadCount: 2450,
    url: "https://pan.baidu.com/s/1Wth1W9abKGBeW_yob-cypQ?pwd=4ugp",
    date: "2024-10-15",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 2,
    title: "ExtendScript ScriptUI 开发指南",
    category: "script",
    description: "专注ScriptUI界面设计，提供控件创建、布局优化及事件处理方案，助力开发者构建直观的AE脚本交互界面，提升用户体验。",
    icon: "📄",
    fileSize: "2.2 MB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1wUfBYdi2kQu0JVGUY_-GoA?pwd=6pd7",
    date: "2024-10-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 3,
    title: "AE表达式自学神器AE_Expr_Tool v1.0",
    category: "script",
    description: "原创AE脚本，一键查询内置表达式功能说明并配备用法示例，支持快速为选中图层属性添加自定义表达式，提升表达式编辑效率，适合动画师与特效师使用。",
    icon: "⚙️",
    fileSize: "732 KB",
    version: "原创脚本",
    downloadCount: 939,
    url: "../../assets/downloads/scripts/layer-manager.zip",
    date: "2024-10-05",
    priceType: "收费",
    price: "¥35.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 4,
    title: "AE脚本开发全套视频教程及配套文档",
    category: "script",
    description: "原创After Effects ExtendScript 脚本开发视频教程，包含脚本开发及scriptUI设计教程，并配有章节文档，提高用户脚本开发能力。",
    icon: "🎬",
    fileSize: "5.35 GB",
    version: "视频教程文档",
    downloadCount: 329,
    url: "../../assets/downloads/scripts/layer-manager.zip",
    date: "2025-02-08",
    priceType: "收费",
    price: "¥298.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 5,
    title: "AE效果属性匹配名称查询工具",
    category: "script",
    description: "一款通过输入AE本地化名称可以查询到相应的匹配名称工具，配有使用文档，提高用户脚本开发效率。",
    icon: "⚙️",
    fileSize: "733 KB",
    version: "原创脚本",
    downloadCount: 2646,
    url: "https://pan.baidu.com/s/1P_qHeSXHht3lJyDevSZJjg?pwd=6yif",
    date: "2018-08-01",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 6,
    title: "图片转码脚本Base64Imager v1.0",
    category: "script",
    description: "Base64Imager v1.0 是一款能够将图片文件转换成Base64编码格式脚本，适合网页动画制作、UI设计和需要内嵌图片资源的项目",
    icon: "⚙️",
    fileSize: "682 KB",
    version: "原创脚本",
    downloadCount: 1957,
    url: "https://pan.baidu.com/s/1vDiSgpvgxEaNeQHojMxW5w?pwd=p8pf",
    date: "2018-08-08",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 7,
    title: "素材搜索器MaterialSearch v1.0",
    category: "script",
    description: "素材搜索器是一款专为Adobe After Effects设计的效率工具，支持模糊搜索项目面板中的素材，并通过直观的界面快速定位目标素材，大幅提升工作流程效率。",
    icon: "⚙️",
    fileSize: "726 KB",
    version: "原创脚本",
    downloadCount: 1153,
    url: "https://pan.baidu.com/s/14rHo6-Yrur059jOido6xJw?pwd=u5xh",
    date: "2025-10-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 8,
    title: "素材搜索器MaterialSearch v2.0",
    category: "script",
    description: "素材搜索器 v2.0在v1.0搜索功能基础上新增了素材导入和替换功能。支持模糊搜索项目面板中的素材，快速定位目标素材，并能够安全地导入和替换素材。",
    icon: "⚙️",
    fileSize: "782 KB",
    version: "原创脚本",
    downloadCount: 1641,
    url: "https://pan.baidu.com/s/1Urg9_sVvMeVTXwK4Gh-lCQ?pwd=c4u6",
    date: "2025-10-13",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 9,
    title: "图层离散器Layer Disperser v1.0",
    category: "script",
    description: "图层离散器是一款专业图层离散化脚本。它通过先进的离散算法，将单一图层智能拆解为具有空间分布的多元素组合，广泛应用于动态图形设计、视觉特效制作、片头包装等领域.",
    icon: "⚙️",
    fileSize: "823 KB",
    version: "原创脚本",
    downloadCount: 3521,
    url: "https://pan.baidu.com/s/1Rq_s8uSqjP_GFZkegl7TQw?pwd=e7i9",
    date: "2025-10-15",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 10,
    title: "字符串转Unicode v1.0",
    category: "script",
    description: "一款专为AE脚本开发者设计的专业安全工具。通过将明文字符串转换为Unicode转义序列，保护脚本中的敏感信息，如注册密钥、授权码等，防止普通用户直接查看源代码中的关键数据。",
    icon: "🔧",
    fileSize: "765 KB",
    version: "原创脚本",
    downloadCount: 1052,
    url: "https://pan.baidu.com/s/1byMUc6T5GvlfbN8-cwNtkg?pwd=a673",
    date: "2025-10-16",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 11,
    title: "Unicode转义序列转字符串 v1.0",
    category: "script",
    description: "Unicode转义序列转字符串工具是一款专为After Effects脚本开发者设计的专业安全工具。本产品通过将Unicode转义序列转换为明文字符串。",
    icon: "🔧",
    fileSize: "713 KB",
    version: "原创脚本",
    downloadCount: 1627,
    url: "https://pan.baidu.com/s/1vPcRUo_RXBh6Rkh_Ucxq3g?pwd=s5yh",
    date: "2025-10-16",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 12,
    title: "属性路径获取工具 v1.0",
    category: "script",
    description: "Property Path Generator 是一款专业的 After Effects 脚本工具，专门为 AE 脚本开发者设计。它可以自动生成精确的属性引用路径代码，极大提高开发效率。",
    icon: "🔧",
    fileSize: "773 KB",
    version: "原创脚本",
    downloadCount: 2162,
    url: "https://pan.baidu.com/s/1JbbKiBCtIvFbTfFMfQPlig?pwd=jy7d",
    date: "2025-10-24",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 13,
    title: "预合成助手 PreComp Assistant v2.0",
    category: "script",
    description: "预合成助手是一款专业的After Effects脚本工具，用于简化预合成和解预合成操作。通过智能的时间保持和图层顺序管理，让您的合成工作流程更加高效顺畅。",
    icon: "📜",
    fileSize: "763 KB",
    version: "原创脚本",
    downloadCount: 3018,
    url: "https://pan.baidu.com/s/1Zy1U_dvVeT7FbF1qTpf6rw?pwd=ixf3",
    date: "2025-10-27",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },

  // ==================== 表达式分类  ====================
  {
    id: 101,
    title: "Adobe After Effects表达式官方文档",
    category: "expression",
    description: "AE表达式官方文档详细解析了JS语法在动画控制中的核心应用，涵盖基础运算符、时间轴控制、对象属性绑定等关键功能，是动态图形设计的权威技术指南。",
    icon: "📜",
    fileSize: "694 KB",
    version: "文档",
    downloadCount: 1765,
    url: "https://pan.baidu.com/s/1aqIphvWt9ETwWQovlh_Sqg?pwd=uxx8",
    date: "2024-09-28",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 102,
    title: "AE表达式视频教程",
    category: "expression",
    description: "零基础入门到精通，表达式视频教程。包含15个章节。配有相应的表达式工程文件及解说文档",
    icon: "▶️",
    fileSize: "7.8 GB",
    version: "视频教程",
    downloadCount: 552,
    url: "../../assets/downloads/expressions/expression-presets.zip",
    date: "2024-09-15",
    priceType: "收费",
    price: "¥198.00",
    qrCode: "../../assets/images/qq_image.png"
  },

  // ==================== 插件分类  ====================
  {
    id: 201,
    title: "Premiere Pro UXP 插件开发系统教程",
    category: "plugin",
    description: "让Premiere听懂你的指令。通过UXP开发增效面板，把复杂流程一键封装，从剪辑师进阶为工具创造者。",
    icon: "📹",
    fileSize: "6.15 GB",
    version: "视频教程",
    downloadCount: 1039,
    url: "../../assets/downloads/templates/text-animations.zip",
    date: "2026-05-20",
    priceType: "收费",
    price: "¥398.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 202,
    title: "Adobe After Effects UXP 插件开发入门指南",
    category: "plugin",
    description: "为AE注入灵魂！告别重复操作，开启UXP插件开发之旅，从使用者变身创造者，打造专属神器",
    icon: "📹",
    fileSize: "6.9 GB",
    version: "视频教程",
    downloadCount: 678,
    url: "../../assets/downloads/templates/text-animations.zip",
    date: "2024-08-20",
    priceType: "收费",
    price: "¥598.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 203,
    title: "UXP JavaScript API 与开发指南",
    category: "plugin",
    description: "这份文档详细介绍了 UXP 插件的核心 JavaScript API 及基本开发流程与方法。",
    icon: "📋",
    fileSize: "4.8 MB",
    version: "文档",
    downloadCount: 1324,
    url: "https://pan.baidu.com/s/19acCU_yFJFCjq1FnnMsG_A?pwd=de6k",
    date: "2024-09-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 204,
    title: "UXP 样式与 CSS 指南",
    category: "plugin",
    description: "该指南说明了如何使用 CSS 来定义和美化 UXP 插件用户界面的外观与样式。",
    icon: "📚",
    fileSize: "723 KB",
    version: "文档",
    downloadCount: 1543,
    url: "https://pan.baidu.com/s/1Qw0P-5OlR7Sb4PiSh_vfow?pwd=eedr",
    date: "2024-09-05",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 205,
    title: "UXP 界面结构与 HTML 指南",
    category: "plugin",
    description: "本指南阐述了如何使用 HTML 来构建和定义 UXP 插件的用户界面基础结构。",
    icon: "✏️",
    fileSize: "466 KB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1D6NTBRHGYoxu_xPmqlGFDg?pwd=irpm",
    date: "2024-08-28",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 206,
    title: "Adobe Spectrum组件库指南",
    category: "plugin",
    description: "此指南介绍了如何调用官方的 Spectrum UI 组件库，以确保插件界面与 Adobe 家族风格一致。",
    icon: "📝",
    fileSize: "7.9 MB",
    version: "文档",
    downloadCount: 1876,
    url: "https://pan.baidu.com/s/1uzIDb3uwxQJqOl-xj07tZg?pwd=uruc",
    date: "2024-08-25",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },


  // ==================== 项目模板分类  ====================

  {
    id: 301,
    title: "AE表达式-条件逻辑(If语句)工程文件",
    category: "template",
    description: "该AE工程文件通过具体示例，演示了if条件语句在After Effects表达式中的编写语法与应用方法。",
    icon: "🔄",
    fileSize: "249 KB",
    version: "工程文件",
    downloadCount: 2210,
    url: "https://pan.baidu.com/s/1zoQ2vuOm51nXhjAbrCK9LA?pwd=h3de",
    date: "2024-08-15",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },


  // ==================== 自研软件分类  ====================

  {
    id: 401,
    title: "AE脚本界面设计器ScriptUI Designer v1.0.0",
    category: "software",
    description: "AE脚本UI设计器是一款专业的AE脚本用户界面设计工具，帮助用户快速设计和生成AE脚本的UI界面。请在【软件指南】栏目查看相关下载以及购买使用视频",
    icon: "🖥️",
    fileSize: "92 MB",
    version: "自研软件",
    downloadCount: 276,
    url: "https://pan.baidu.com/s/16jn8BpSuvXqceltcQjLdBw?pwd=b26n",
    date: "2025-10-29",
    priceType: "收费",
    price: "¥58.00",
    qrCode: "../../assets/images/qq_image.png"
  },
  {
    id: 402,
    title: "MarkdownToHtml转换器Markdown Wizard v1.0.0",
    category: "software",
    description: "一款轻量级桌面应用，集编辑、转换、预览于一体，让你的写作与发布流程无缝衔接。请在【软件指南】栏目查看相关使用视频",
    icon: "🔄",
    fileSize: "73.5 MB",
    version: "自研软件",
    downloadCount: 953,
    url: "https://pan.baidu.com/s/1D3d7UhWkZ27FFjYii_It-A?pwd=k8xd",
    date: "2025-11-11",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 403,
    title: "PDF水印添加工具PDF Watermark Tool v1.0.0",
    category: "software",
    description: "PDF Watermark Tool 是一款专业的PDF水印添加工具，支持快速为PDF文档添加自定义水印。请在【软件指南】栏目查看相关使用视频",
    icon: "💦",
    fileSize: "66.8 MB",
    version: "自研软件",
    downloadCount: 325,
    url: "https://pan.baidu.com/s/1J0iPlm5XHUvQ9OJ1qG34Cw?pwd=bq5a",
    date: "2025-11-24",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 404,
    title: "AE英文学习助手AE Terminology learning v1.0.0",
    category: "software",
    description: "AE英文界面学习助手是一款帮助英文基础薄弱的用户快速熟悉和掌握AE英文版界面中的专业术语。请在【软件指南】栏目查看相关使用视频",
    icon: "🔤",
    fileSize: "68.6 MB",
    version: "自研软件",
    downloadCount: 975,
    url: "https://pan.baidu.com/s/1Goj5vNN6i4hU1UBJZ0jTng?pwd=ni5p",
    date: "2025-12-08",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 405,
    title: "AE英文学习助手AE Word Master v2.0.0",
    category: "software",
    description: "AE英文界面学习助手是一款帮助英文基础薄弱的用户快速熟悉和掌握AE英文版界面中的专业术语。请在【软件指南】栏目查看相关使用视频",
    icon: "🔤",
    fileSize: "75 MB",
    version: "自研软件",
    downloadCount: 1026,
    url: "https://pan.baidu.com/s/1muKzxJsYuPNQUhpX-FG2ng?pwd=2vgv",
    date: "2026-01-14",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 406,
    title: "文本转语音合成工具TTS",
    category: "software",
    description: "文本转语音合成工具TTS是一款能够将文本转成语音的工具。请在【软件指南】栏目查看相关使用视频",
    icon: "🔉📄",
    fileSize: "73 MB",
    version: "自研软件",
    downloadCount: 568,
    url: "#",
    date: "2026-01-26",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 407,
    title: "音梳 v1.0.0",
    category: "software",
    description: "音梳(Audio Comber)是一款专业音效管理工具。它能够帮助您高效地管理、预览、处理和导出音频素材。请在【软件指南】栏目查看相关使用视频",
    icon: "🎵",
    fileSize: "98.6 MB",
    version: "自研软件",
    downloadCount: 1236,
    url: "https://pan.baidu.com/s/1ESdpjIE62YJJZPhRpmVVfA?pwd=2g7b",
    date: "2026-01-26",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 408,
    title: "音梳 v2.0.0",
    category: "software",
    description: "音梳(Audio Comber)是一款专业音效管理工具。它能够帮助您高效地管理、预览、处理和导出音频素材。请在【软件指南】栏目查看相关使用视频",
    icon: "🎵",
    fileSize: "175 MB",
    version: "自研软件",
    downloadCount: 669,
    url: "#",
    date: "2026-02-12",
    priceType: "收费",
    price: "¥29.80",
    qrCode: "../../assets/images/qq_image.png"
  },

  // ==================== 外部工具分类  ====================
  {
    id: 501,
    title: "Adobe UXP Developer Tools",
    category: "toolkit",
    description: "Adobe官方提供的插件开发工具集，专门用于在现代 UXP 平台上为 Creative Cloud 应用程序（如 PS、PR、AE）开发插件。",
    icon: "🔧",
    fileSize: "3.1 MB",
    version: "v2.1",
    downloadCount: 2987,
    url: "https://creativecloud.adobe.com/apps/download/uxp-developer-tools",
    date: "2025-02-10",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 502,
    title: "RGB颜色对照表",
    category: "toolkit",
    description: "该文档汇编了各种颜色的英文名称、RGB数值、实色效果块及其对应的16进制颜色代码。",
    icon: "🎨",
    fileSize: "353 KB",
    version: "文档",
    downloadCount: 1987,
    url: "https://pan.baidu.com/s/1khTvZ4gvobQBJqfJYoJfTg?pwd=fmmd",
    date: "2024-08-05",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 503,
    title: "Adobe ExtendScript Toolkit CC",
    category: "toolkit",
    description: "ESTK是Adobe系列软件的专用脚本编辑器，用于编写和调试ExtendScript脚本，以自动化执行Photoshop、AE等软件任务。",
    icon: "⌨️",
    fileSize: "93.8 MB",
    version: "v4.0.0.1",
    downloadCount: 416,
    url: "https://pan.baidu.com/s/1Zf2bDv2EWqF16Kkmj-Km4Q?pwd=pgwc",
    date: "2010-08-06",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },
  {
    id: 504,
    title: "Visual Studio Code",
    category: "toolkit",
    description: "VS Code是一款轻量级代码编辑器，支持多种编程语言，具备强大的扩展功能，帮助开发者高效编写、调试和管理项目。",
    icon: "🔨",
    fileSize: "98.6 MB",
    version: "v1.104.2",
    downloadCount: 3432,
    url: "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user",
    date: "2025-08-06",
    priceType: "免费",
    price: "免费",
    qrCode: ""
  },

];